# Generated by Django 4.1.7 on 2023-07-10 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_descrition', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='upload_product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercustomer', models.CharField(default='None', max_length=100)),
                ('how_many', models.IntegerField()),
                ('total', models.IntegerField()),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('prime_pk', models.IntegerField(default=0)),
                ('orderconform', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.upload_product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
